apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-dokument
  labels:
    team: bidrag
spec:
  image: repo.adeo.no:5443/bidrag-dokument:{{version}}
  port: 8080
  liveness:
    path: /bidrag-dokument/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-dokument/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-dokument/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - {{ingress}}
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvbisys
        mountPath: /var/run/secrets/nais.io/srvbisys
      - kvPath: /kv/preprod/fss/bidrag-dokument/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault