apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-dokument
  namespace: {{ namespace }}
  labels:
    team: bidrag
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /bidrag-dokument/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-dokument/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-dokument/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - https://bidrag-dokument.nais.adeo.no/
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvbisys
        mountPath: /var/run/secrets/nais.io/srvbisys
      - kvPath: /kv/prod/fss/bidrag-dokument/default
        mountPath: /var/run/secrets/nais.io/vault