####################################################################
# 
# Profiles: All
#							
####################################################################

server:
  servlet:
    context-path: /bidrag-dokument
management:
  endpoints:
    web:
      exposure:
        include: "*"

---

####################################################################
# 
# Profiles: live
#							
####################################################################

spring:
  profiles: live

# OIDC          
no.nav.security.oidc:
  issuers: isso
  issuer:
    isso:
      acceptedaudience: bidrag-ui-master-${FASIT_ENVIRONMENT_NAME}, bidrag-dokument-ui-${FASIT_ENVIRONMENT_NAME}
      discoveryurl: ${ISSO_ISSUER_URL}/.well-known/openid-configuration

---

####################################################################
# 
# Profiles: test, secure-test
#
# Use test token
#							
####################################################################

spring:
  profiles: test, secure-test

no.nav.security.oidc:
  issuers: isso
  issuer.isso:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

---