server:
  servlet:
    context-path: /bidrag-dokument
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
TOKEN_OBTAINED_BY: bidrag-dokument-ui
        
no.nav.security.oidc.issuer.isso.acceptedaudience: ${TOKEN_OBTAINED_BY}-${FASIT_ENVIRONMENT_NAME}
no.nav.security.oidc.issuer.isso.discoveryurl: ${ISSO_ISSUER_URL}/.well-known/openid-configuration
