
bidrag-dokument:
  restservice:
    finn: https://bidrag-dokument/journalpost/finn/for/
    hent: https://bidrag-dokument/journalpost/hent/
joark:
  url: https://joark/journalforing/hent/
journalpost:
 url: https://bidrag-journalpost/sak/
server:
  servlet:
    context-path: /bidrag-dokument
management:
  endpoints:
    web:
      exposure:
        include: "*"
