joarkURL: https://joark/journalforing/hent/
journalpostURL: https://bidrag-journalpost/aaaa
server:
  servlet:
    context-path: /bidrag-dokument
management:
  endpoints:
    web:
      exposure:
        include: "*"
