name: continious integration
on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - name: debug
        run: env
      - name: cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: setup maven
        uses: navikt/bidrag-actions/setup-maven@feature-mvn-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify that no dependencies are of type SNAPSHOT
        uses: navikt/bidrag-actions/verify-mvn-dependencies@feature-mvn-app
      - name: build & test with maven
        run: |
          cat ~/.m2/settings.xml
          mvn -B install
      - name: prepare release of nais application
        if: github.ref == 'refs/heads/master'
        uses: navikt/bidrag-actions/release-prepare-mvn-pkg@master
        with:
          new_snapshot_version_file_name: .new-snapshot-version
          release_version_file_name: .release-version
#      - name: commit new version
#        if: github.ref == 'refs/heads/master'
#        uses: navikt/bidrag-actions/tag-and-commit@master
#        with:
#          message: Bumped to new version after release of version {}
#          pattern: pom.xml
#          tag_file: .release-version
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
