name: continious integration
on:
  push:
    branches:
      - '**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/bidrag-dokument:${{ github.sha }}

jobs:

  build:
    name: Build with maven and docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: '13'
      - run: env
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: navikt/bidrag-actions/setup-maven@v4.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: navikt/bidrag-actions/maven-verify-dependencies@feature-maven
      - run: mvn install -B -e
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - if: github.ref == 'refs/heads/master'
        run: mvn release:update-versions
      - if: github.ref == 'refs/heads/master'
        run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > .new-version
      - if: github.ref == 'refs/heads/master'
        uses: navikt/bidrag-actions/git-commit@v4.0.7
        with:
          commit_message: "Bumped to new version: {}"
          commit_message_file: .new-version
          pattern: "pom.xml"

  deploy_dev:
    runs-on: ubuntu-latest
    name: Deploy docker image to dev
    if: github.ref != 'refs/heads/release'
    needs: build

    steps:
      - uses: actions/checkout@v2
        with:
          path: deploy
      - name: Deploy to dev-fss, default namespace
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/nais.yaml
          VAR: namespace=default,ingress=https://bidrag-dokument.nais.preprod.local/
      - name: Deploy to dev-fss, namespace q1
        if: github.ref != 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/nais.yaml
          VAR: namespace=q1,ingress=https://bidrag-dokument-q1.nais.preprod.local/

  bump_dev_version:
    runs-on: ubuntu-latest
    name: bump SNAPSHOT version
    if: github.ref == 'refs/heads/master'
    needs: deploy_dev

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn release:update-versions
      - run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > .new-version
      - uses: navikt/bidrag-actions/git-commit@v4.0.7
        with:
          commit_message: "Bumped to new version: {}"
          commit_message_file: .new-version
          pattern: "pom.xml"

  run_cucumber:
    runs-on: self-hosted
    name: Run cucumber integration tests
    needs: deploy_dev
    steps:
      - run: echo "If failures, then fix and run cucumber test suite manual"
      - name: run cucumber backend tests for q1
        uses: navikt/bidrag-actions/cucumber-jvm@feature-maven
        if: github.ref != 'refs/heads/master'
        with:
          cucumber_tags: bidrag-dokument
          environment: q1
          maven_image: maven:3.6.3-jdk-13
        env:
          MAVEN_CUCUMBER_CREDENTIALS: ${{ secrets.MAVEN_CUCUMBER_CREDENTIALS }}
      - name: run cucumber backend tests for default namespace (q0)
        uses: navikt/bidrag-actions/cucumber-jvm@feature-maven
        if: github.ref == 'refs/heads/master'
        with:
          cucumber_tags: bidrag-dokument
          environment: q0
          maven_image: maven:3.6.3-jdk-13
        env:
          MAVEN_CUCUMBER_CREDENTIALS: ${{ secrets.MAVEN_CUCUMBER_CREDENTIALS }}

  deploy_prod:
    runs-on: ubuntu-latest
    name: Deploy docker image to prod
    if: github.ref == 'refs/heads/release'
    needs: build

    steps:
      - uses: actions/checkout@v2
        with:
          path: deploy
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: deploy/nais-p.yaml
          VAR: namespace=default

  tag_prod_deploy:
    runs-on: ubuntu-latest
    name: Tag latest deploy to prod
    needs: deploy_prod

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//' > .tag-version
      - uses: navikt/bidrag-actions/git-tag@v4.0.2
        with:
          tag_message: Releasing version {}
          tag_file: .tag-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
