name: continious integration
on:
  push:
    branches:
      - '**'

jobs:

  build:
    name: Build maven jar and docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - run: env
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: navikt/bidrag-actions/setup-maven@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify that no dependencies are of type SNAPSHOT
        uses: navikt/bidrag-actions/verify-mvn-dependencies@v1.0.0
      - name: Build & test with maven
        run: mvn -B install
      - name: Create Docker tag & image
        run: |
          echo "docker.pkg.github.com"/"$GITHUB_REPOSITORY"/"$(echo $GITHUB_REPOSITORY | sed 's;^.*/;;')" > .docker-image
          echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" > .docker-tag
      - name: Build Docker image
        run: docker build -t $(cat .docker-image):$(cat .docker-tag) .

  deploy:
    runs-on: ubuntu-latest
    name: Deploy docker-image as nais application
    needs: build

    steps:
      - run: echo "todo"

